/**
 * lecture1.js — MBSE & SysML Course Portal · Wright State University
 * ─────────────────────────────────────────────────────────────────────
 * Lecture 1: Foundations of Systems Architecture & The Mathematical
 * Imperative for MBSE
 *
 * Data format consumed by index.html's renderEngine.
 * To add this lecture, place file in the same directory as index.html.
 * The window.registerLecture() hook fires after the script evaluates.
 * ─────────────────────────────────────────────────────────────────────
 */
(function () {
  "use strict";

  const LECTURE_1_DATA = {

    /* ═══════════════════════════════════════════════════════════════
       META  ─  course metadata block
       ═══════════════════════════════════════════════════════════════ */
    meta: {
      id:           1,
      week:         1,
      unit:         'Foundations',
      title:        'Foundations of Systems Architecture & The Mathematical Imperative for MBSE',
      duration:     '90 min',
      difficulty:   'Introductory',
      creditHours:  3,
      studyHours:   '3–4 hrs',
      tools:        ['CATIA Magic 2024x', 'Papyrus (SysML)', 'PlantUML'],
      prerequisites: ['Introductory Systems Engineering or concurrent enrollment'],
      objectives: [
        'Define a system and explain emergent behavior',
        'Articulate why document-centric workflows fail at scale',
        'State the four pillars of SysML and their roles',
        'Explain the MBSE parametric advantage using an eVTOL weight-snowball example',
        'Identify stakeholders and concerns for a complex engineered system',
        'Distinguish the INCOSE SE Handbook v5 systems lifecycle phases',
      ],
      commonErrors: [
        'Treating MBSE as a diagramming exercise rather than a modeling discipline',
        'Conflating system architecture with software architecture',
        'Ignoring emergent behavior in stakeholder analysis',
      ],
    },

    /* ═══════════════════════════════════════════════════════════════
       CONTENT  ─  academic lecture sections
       ═══════════════════════════════════════════════════════════════ */
    content: [

      /* ── Section 1 ─────────────────────────────────────────────── */
      {
        heading: '1 · What Is a System? Complexity, Emergence, and the Limits of Human Intuition',
        paragraphs: [
          'Engineering, at its most fundamental level, is the discipline of orchestrating complexity in service of human purpose. When practitioners speak of a "system," they invoke a precise technical concept rooted in decades of theoretical development traceable through Bertalanffy\'s general systems theory, Ackoff\'s purposeful systems, and formalized most recently in the INCOSE Systems Engineering Handbook version 5 (2023). A system is a combination of interacting elements organized to achieve a stated purpose within a defined environment. Critically, that purpose and those behaviors are properties of the whole that cannot be attributed to any single constituent part in isolation — this is the phenomenon engineers call emergent behavior.',
          'Emergence is not a curiosity; it is the central engineering challenge. The lift generated by a complete aircraft wing cannot be predicted from the airfoil cross-section alone without accounting for spanwise pressure gradients, induced drag coupling, and compressibility effects at transonic speeds. The safety integrity of an eVTOL autopilot cannot be guaranteed by examining its flight-control computer in isolation, divorced from the power distribution architecture, the battery management system, the pilot-vehicle interface, and the regulatory operational design domain. Emergence means that system-level requirements can only be satisfied, verified, and traced through an integrated model of the whole — not through a collection of independently authored specification documents.',
          'The INCOSE Handbook v5 defines the systems engineer\'s primary task as identifying, bounding, and architecting the system of interest (SOI) such that all stakeholder concerns are captured, translated into verifiable requirements, and allocated to architectural elements in a manner that supports lifecycle decisions from concept through disposal. This framing immediately reveals why the traditional document-centric paradigm — requirements in a Word document, interfaces in a spreadsheet, trade studies in a standalone MATLAB script, verification records in another spreadsheet — is structurally inadequate for any system of meaningful complexity.',
        ],
        callout: {
          type: 'standard',
          label: 'INCOSE Definition — System of Interest (SOI)',
          body: 'The system of interest (SOI) is the system whose life cycle is under consideration in the context of a given situation. It is bounded by a system boundary that separates it from the system\'s operating environment, including enabling systems, other systems in the environment, and the SOI\'s operational context. — INCOSE SE Handbook v5, Section 2.3.',
        },
      },

      /* ── Section 2 ─────────────────────────────────────────────── */
      {
        heading: '2 · The Document-Centric Failure Mode — An Anatomy',
        paragraphs: [
          'Before an engineer can appreciate why Model-Based Systems Engineering represents a genuine paradigm shift rather than a productivity tool, they must understand the specific failure modes that document-centric workflows exhibit at scale. These failures are not merely organizational inefficiencies; they are structural artifacts of storing engineering knowledge in natural-language prose and disconnected spreadsheets rather than in a formally consistent, machine-traversable model.',
          'The four canonical failure modes of document-centric engineering are: (1) requirement inconsistency across documents — the same performance parameter is stated differently in the system specification, the subsystem interface control document, and the test procedure, and no automated mechanism reconciles the divergence; (2) stale traceability — a change to a parent requirement is recorded in one document but the downstream allocation documents are not regenerated, leaving engineers unaware that forty lower-level requirements and twelve verification cases are now orphaned or inconsistent; (3) siloed analysis — mass properties live in a CATIA model, power budgets in an Excel workbook, and thermal margins in a separate MATLAB script, with no binding connector that propagates a change in battery cell density through to the revised power margin and the revised MTOW simultaneously; and (4) review latency — design reviews are gated by the availability of documents rather than the maturity of the model, introducing multi-week delays because engineers must manually re-extract information that already exists in disconnected tool outputs.',
        ],
        callout: {
          type: 'gold',
          label: 'eVTOL Sizing Case Study — The MTOW Snowball Effect',
          body: '<strong>The Document-Centric Error.</strong> Consider a preliminary design team sizing an eVTOL air-taxi using a static spreadsheet workflow. An aerodynamicist derives a hover power estimate, a propulsion engineer computes rotor disk loading, and a structures lead sizes the airframe — each working from separate documents issued at a single point in time. The spreadsheet-based mass budget converges on a Maximum Takeoff Weight (MTOW) of 1,722 kg. This figure satisfies the initial stakeholder requirement of "MTOW ≤ 1,800 kg." The design is baselined. <br><br><strong>The Hidden Coupling.</strong> What the document workflow fails to propagate is the iterative dependency between battery mass, hover power demand, and structural weight. The initial battery sizing was performed at a discharge rate sufficient for cruise, not peak hover. Accounting for the true 5-minute emergency hover reserve at 115% rated power increases the required battery energy by 31%. The additional battery mass — 187 kg — increases structural load, which increases airframe mass, which further increases hover power demand. Each cycle of this weight snowball adds incremental mass. <br><br><strong>The MBSE Parametric Solution.</strong> A SysML parametric model with binding connectors propagates every design variable change automatically. The parametric diagram binds the battery mass property to the structural load constraint block, which binds to the rotor power constraint block, which feeds back to the battery sizing equation. When the hover reserve requirement is correctly encoded, the model iteratively converges — within milliseconds — to the physically consistent MTOW of <strong>2,969 kg</strong>: a 72.4% underestimation by the document-centric approach, directly comparable to validated findings from the Wright State MATLAB–MBSE integrated sizing framework (Northam & Chen, 2025). A design cleared for preliminary design review at 1,722 kg would be structurally undersized, rotor-undersized, and power-budget-negative in actual hover operations.',
        },
        equations: [
          'MTOW_document = 1,722 kg  [static spreadsheet, cruise-only battery sizing]',
          'MTOW_MBSE     = 2,969 kg  [parametric model, hover-reserve-correct battery mass]',
          'Error         = (2,969 − 1,722) / 1,722 × 100% = 72.4% underestimation',
          'Parametric binding:  m_battery → F_structural → P_hover → m_battery  [iterative loop]',
        ],
      },

      /* ── Section 3 ─────────────────────────────────────────────── */
      {
        heading: '3 · Model-Based Systems Engineering — Definition, Scope, and Formal Grounding',
        paragraphs: [
          'The INCOSE definition, now codified in SE Handbook v5, characterizes MBSE as the formalized application of modeling to support system requirements, design, analysis, verification, and validation activities beginning in the conceptual design phase and continuing throughout development and later life cycle phases. Three words in that definition carry exceptional weight: "formalized," "support," and "continuing." Formalized means that the models are constructed according to a defined language with normative semantics — not freehand sketches, not PowerPoint boxes, but elements with rigorously defined meaning under a published standard. Support means that the models are not the deliverable; they are the engineering environment through which decisions are made, evidence is generated, and knowledge is transferred. Continuing means that the model is a living artifact updated at every phase gate, not frozen at PDR and forgotten.',
          'The Object Management Group\'s Systems Modeling Language version 1.7 (OMG SysML 1.7), maintained as ISO/IEC 19514:2017, is the normative formal language for MBSE in current industry practice. SysML is a profile of the Unified Modeling Language (UML) 2.5.1, extended to address the full spectrum of systems engineering concerns beyond software. It provides four categories of diagram, commonly referred to as the four pillars: requirements diagrams for capturing and tracing stakeholder needs; structural diagrams — block definition diagrams (BDD) and internal block diagrams (IBD) — for describing system composition and interfaces; behavioral diagrams — activity, sequence, state machine, and use case diagrams — for specifying how the system operates; and parametric diagrams for encoding engineering constraints and enabling quantitative analysis within the model itself.',
        ],
        subsections: [
          {
            title: 'The Four Pillars of SysML 1.7',
            paragraphs: [
              'Requirements diagrams capture stakeholder needs, system requirements, and the traceability relationships among them — derive, refine, trace, satisfy, and verify. They are the contractual backbone of the model, linking every architectural decision back to an original stakeholder concern.',
              'Structural diagrams describe what the system is made of. The Block Definition Diagram (BDD) defines types — blocks, their properties, and the associations between them at the classification level. The Internal Block Diagram (IBD) reveals the instance-level internal architecture: how part properties connect through ports and item flows within the context of a specific block. Together, BDD and IBD provide the complete structural picture of the system of interest.',
              'Behavioral diagrams describe what the system does. Activity diagrams model functional flow, functional allocation, and process logic. Sequence diagrams expose time-ordered interactions across system boundaries. State machine diagrams capture lifecycle logic and mode management. Use case diagrams describe externally visible services from the stakeholder\'s perspective.',
              'Parametric diagrams are the analytical heart of SysML and the dimension that most decisively separates it from document-centric practice. A constraint block encodes an engineering equation — mass budget, power balance, structural load, thermal margin — as a first-class model element. Binding connectors wire the value properties of structural blocks to the variables of constraint blocks, enabling the model to propagate quantitative changes automatically across the entire design space. The eVTOL MTOW snowball example from Section 2 is precisely the class of problem that parametric diagrams are designed to solve.',
            ],
            callout: {
              type: 'standard',
              label: 'OMG SysML 1.7 — Normative Pillars',
              body: 'SysML 1.7 provides nine diagram types organized across four pillars: (1) Requirements — Requirement Diagram; (2) Structure — Block Definition Diagram, Internal Block Diagram, Package Diagram; (3) Behavior — Activity Diagram, Sequence Diagram, State Machine Diagram, Use Case Diagram; (4) Parametric — Parametric Diagram. These nine diagrams share a common metamodel pool of approximately 800 named metaclasses and are the normative vocabulary of MBSE in aerospace and defense as of the writing of this course.',
            },
          },
        ],
      },

      /* ── Section 4 ─────────────────────────────────────────────── */
      {
        heading: '4 · The INCOSE Systems Engineering Lifecycle — Decision Gates and the MBSE Thread',
        paragraphs: [
          'The INCOSE SE Handbook v5 organizes the systems lifecycle into six stages: concept definition, system definition, system realization, system integration and verification, system qualification and transition, and operations and maintenance. Each stage is bounded by decision gates at which program leadership, customer representatives, and technical authority must confirm that the system model — and the evidence it contains — is sufficiently mature to authorize the next stage of investment. The traditional gate reviews — Mission Concept Review (MCR), System Requirements Review (SRR), Preliminary Design Review (PDR), Critical Design Review (CDR) — are therefore not document reviews. They are model reviews. The data package presented at each gate should be extractable from the authoritative model, not assembled from disparate document silos the week before the review.',
          'This architectural framing of the lifecycle has a profound practical implication for the MBSE practitioner: the model must be structured, governed, and maintained with the same engineering rigor applied to the system it represents. Package architecture, naming conventions, model element maturity levels, version control branching strategy, and model quality gates are not administrative concerns. They are technical disciplines that determine whether the model remains a trustworthy engineering asset or degrades into an elaborate diagram collection that no one believes.',
        ],
      },

      /* ── Section 5 ─────────────────────────────────────────────── */
      {
        heading: '5 · Stakeholder Analysis — Who Defines the System?',
        paragraphs: [
          'A system exists to deliver value to stakeholders. A stakeholder, in the INCOSE sense, is any individual, organization, or system that has an interest in the performance, operation, or outcome of the system of interest. Stakeholders are not limited to paying customers; the taxonomy includes primary users who operate the system, secondary users who are affected by its operation, regulatory bodies that impose safety and environmental constraints, maintainers who must service the system throughout its operational life, and the system itself in the case of automated self-monitoring. Correctly identifying and characterizing stakeholders before beginning any architectural work is the single most effective mechanism for preventing requirements omission errors — the class of defect that is, by wide engineering consensus, the most expensive to correct once a design is baselined.',
          'For the autonomous Mars rover — the subject of this lecture\'s assignment — the stakeholder taxonomy spans mission scientists who define scientific objectives, NASA and ESA mission directors who impose cost and schedule constraints, JPL engineers who must launch the rover as a payload and therefore constrain mass and volume, surface operations teams who monitor and command the rover in real time with a 3-to-22-minute one-way communication delay, and the rover itself as an autonomous agent whose operational context requires a clearly bounded system-of-interest definition. Each stakeholder class holds distinct concerns, and those concerns must be individually captured, resolved for conflicts, and transformed into system-level requirements before any block definition diagram is drawn.',
        ],
      },

      /* ── Section 6 ─────────────────────────────────────────────── */
      {
        heading: '6 · Why SysML Became the Lingua Franca of MBSE',
        paragraphs: [
          'Prior to the publication of OMG SysML 1.0 in 2006, systems engineers had access to a range of informal notations — N² charts, functional flow block diagrams (FFBD), enhanced functional flow block diagrams (EFFBD), IDEF0 functional decompositions, and proprietary tool-specific notations. Each addressed a specific engineering concern in isolation, and none provided the integrated model semantics required to propagate a requirement change automatically through structural and behavioral representations and into quantitative parametric constraints. The result was precisely the siloed-analysis failure mode described in Section 2.',
          'SysML addressed this fragmentation by defining a single metamodel — a specification of specifications — that relates requirements, structure, behavior, and parametrics through traceable relationships within one unified architectural environment. A requirement in a requirements diagram can be traced to the block in a BDD that satisfies it, to the port in an IBD through which the required flow is realized, to the activity in an activity diagram that performs the required function, and to the constraint block in a parametric diagram that quantifies the required performance level. This completeness of traceability is the defining technical advantage of SysML over any collection of isolated notations.',
          'The ongoing SysML v2 standardization effort, adopted by OMG in 2024, introduces a textual modeling kernel (KerML) and a significantly restructured metamodel that addresses known limitations of v1, including ambiguities in port and flow semantics and the absence of a native API for tool interoperability. Practitioners entering the discipline now will use SysML 1.7 as the current production standard while preparing for the transition to v2 — a migration path covered in Lecture 22 of this course.',
        ],
        callout: {
          type: 'gold',
          label: 'SysML v1 → v2 Transition Context',
          body: 'OMG formally adopted SysML v2 in March 2024. The v2 standard introduces KerML (Kernel Modeling Language) as a formal semantic foundation, a textual syntax in addition to the graphical one, a restructured port and flow model, and a native API specification for tool integration. Industry adoption is gradual; the major toolchains (CATIA Magic/Cameo, IBM Rhapsody, PTC Integrity Modeler) are releasing v2-capable versions incrementally through 2025–2027. This course is grounded in SysML 1.7 with explicit v2 mapping notes throughout.',
        },
      },

    ], // end content[]

    /* ═══════════════════════════════════════════════════════════════
       REFERENCES
       ═══════════════════════════════════════════════════════════════ */
    references: [
      'INCOSE. (2023). Systems Engineering Handbook v5. International Council on Systems Engineering.',
      'Object Management Group. (2019). OMG Systems Modeling Language v1.7 Specification. OMG Document formal/19-11-01.',
      'Friedenthal, S., Moore, A., & Steiner, R. (2015). A Practical Guide to SysML (3rd ed.). Morgan Kaufmann / OMG Press.',
      'Delligatti, L. (2014). SysML Distilled: A Brief Guide to the Systems Modeling Language. Addison-Wesley.',
      'ISO/IEC 19514:2017. Information technology — Object management group systems modeling language (OMG SysML).',
      'Northam, J., & Chen, R. (2024). Integrated MATLAB-MBSE Parametric Sizing Framework for Urban Air Mobility Aircraft. Journal of Aircraft Systems Engineering, 18(2), 112-128.',
      'Kossiakoff, A., Seymour, S., Flanigan, D., & Hutchison, W. (2011). Systems Engineering Principles and Practice (2nd ed.). Wiley.',
      'Systems-Modeling Organization. (2026). OMG SysML v2 Release Repository [Software]. GitHub. https://github.com/Systems-Modeling/SysML-v2-Release (Includes KerML 1.0, SysML 2.0, and API 1.0 specification documents, normative model libraries, and Eclipse/Jupyter installer packages. Formally adopted by OMG 30 June 2025; updated for ISO submission March 2026.)',
      'Systems-Modeling Organization. (2026). SysML v2 Pilot Implementation [Software, EPL-2.0]. GitHub. https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation (Eclipse Xtext-based reference implementation of the SysML v2 textual notation; includes Jupyter kernel for SysML v2, PlantUML visualization integration, and 85 tagged releases through 2026-04.)',
    ,{heading:'Real-World: Volkswagen Dieselgate — Systems Thinking Failure in Plain Sight',paragraphs:['Volkswagen\'s 2015 emissions scandal — 11 million diesel vehicles programmed to activate emissions controls only during regulatory testing — is a systems thinking failure as much as an ethical one. The defeat device worked because no systems engineer formally modeled the interaction between the emissions control component, the vehicle\'s driving pattern detection system, and the regulatory test cycle protocol. An activity diagram covering the use case Vehicle_Operating_In_Regulatory_Test_Mode, connected to the emissions control component through a formal IBD interface, would have made this coupling visible in the first design review. The defeat device architecture survived precisely because there was no integrated behavioral model of the vehicle as a system.','Apply this to your own models: the most dangerous system behaviors are the unmodeled ones. Every interaction between components that is left as an informal assumption in a designer\'s head — not formalized as a connector, item flow, or state transition — is a potential Volkswagen waiting to be discovered. The function of MBSE is not to document what the design team already knows. It is to make visible what they do not know they have assumed.']},{heading:'Real-World: Airbus A380 Wiring Harness — $4.8 Billion Model Governance Failure',paragraphs:['In 2005, Airbus discovered that the A380 wiring harnesses designed in Germany (CATIA V4) and in France (CATIA V5) were geometrically incompatible. The French wire bundles were sized for the fuselage geometry in CATIA V5. The German harnesses referenced the same geometry in CATIA V4 with a different coordinate standard. When the two fuselage sections joined in Hamburg, the bundles were 14 cm too short. Rework cost: 4.8 billion euros. Root cause: no model governance plan enforcing a single CAD configuration standard across sites.','For your MBSE course: this failure happened not in CATIA Magic but in a CAD tool. But the principle is identical. A governance rule as simple as \'all geometry shall reference AWRF_COORDINATE_SYSTEM_REV_C\' — enforced through automated configuration checks — would have caught the incompatibility before the first section was manufactured. Model governance is not bureaucracy. It is the organizational discipline that prevents a $4.8 billion mistake from occurring silently at integration.']},{heading:'Real-World: Volkswagen Dieselgate — Systems Thinking Failure in Plain Sight',paragraphs:['Volkswagen\'s 2015 emissions scandal — 11 million diesel vehicles programmed to activate emissions controls only during regulatory testing — is a systems thinking failure as much as an ethical one. The defeat device worked because no systems engineer formally modeled the interaction between the emissions control component, the vehicle\'s driving pattern detection system, and the regulatory test cycle protocol. An activity diagram covering the use case Vehicle_Operating_In_Regulatory_Test_Mode, connected to the emissions control component through a formal IBD interface, would have made this coupling visible in the first design review. The defeat device architecture survived precisely because there was no integrated behavioral model of the vehicle as a system.','Apply this to your own models: the most dangerous system behaviors are the unmodeled ones. Every interaction between components that is left as an informal assumption in a designer\'s head — not formalized as a connector, item flow, or state transition — is a potential Volkswagen waiting to be discovered. The function of MBSE is not to document what the design team already knows. It is to make visible what they do not know they have assumed.']},{heading:'Real-World: Airbus A380 Wiring Harness — $4.8 Billion Model Governance Failure',paragraphs:['In 2005, Airbus discovered that the A380 wiring harnesses designed in Germany (CATIA V4) and in France (CATIA V5) were geometrically incompatible. The French wire bundles were sized for the fuselage geometry in CATIA V5. The German harnesses referenced the same geometry in CATIA V4 with a different coordinate standard. When the two fuselage sections joined in Hamburg, the bundles were 14 cm too short. Rework cost: 4.8 billion euros. Root cause: no model governance plan enforcing a single CAD configuration standard across sites.','For your MBSE course: this failure happened not in CATIA Magic but in a CAD tool. But the principle is identical. A governance rule as simple as \'all geometry shall reference AWRF_COORDINATE_SYSTEM_REV_C\' — enforced through automated configuration checks — would have caught the incompatibility before the first section was manufactured. Model governance is not bureaucracy. It is the organizational discipline that prevents a $4.8 billion mistake from occurring silently at integration.']}],

    /* ═══════════════════════════════════════════════════════════════
       SCHEMA VISUALIZER  ─  Tab 2 card data
       ═══════════════════════════════════════════════════════════════ */
    schemaVisualizer: [
      {
        category: 'SysML Core Construct',
        name: 'Block (BDD)',
        diagramType: 'Block Definition Diagram',
        shortDesc: 'The fundamental structural unit. Represents any system element — hardware, software, human, or facility.',
        fullDesc: 'A SysML Block is the most fundamental element in the structural pillar of SysML 1.7. Unlike a UML Class (which is scoped to software objects), a Block can model any system element: a physical component, a software module, a human operator role, a facility, or an abstract logical function. Blocks own properties (parts, values, references, ports) and participate in relationships (composition, association, generalization, dependency). In a Block Definition Diagram (BDD), blocks are shown as rectangles partitioned into compartments by stereotype keyword.',
        notation: [
          'Drawn as a rectangle with a bold border and keyword «block» in double guillemets in the header compartment.',
          'Compartments below the header may declare: parts (filled-diamond compositions), value properties (typed with units), reference properties, constraint properties, operations, and ports.',
          'Compositions in a BDD are shown as solid lines with a filled diamond at the whole-end.',
          'Aggregation (shared ownership) uses an open (hollow) diamond.',
          'Generalization uses a solid line with a hollow triangle arrowhead pointing toward the supertype.',
          'The name of the block is set in bold in the header. If the block is abstract, the name is italicized.',
        ,
{category:'SysML Reference',name:'Nine Diagram Types — Four Pillars',diagramType:'Reference Card',shortDesc:'Complete reference showing all 9 SysML 1.7 diagram types across the 4 pillars. Memorize this map for the midterm and final exam.',fullDesc:'OMG SysML 1.7 (formal/19-11-01, ISO/IEC 19514:2017) organizes nine diagram types across four pillars. Requirements (1): Requirement Diagram. Structure (3): BDD, IBD, Package. Behavior (4): Use Case, Activity, Sequence, State Machine. Parametric (1): Parametric Diagram. Every WSU CEG/EGR 7800 lecture develops one or more of these diagram types. Cross-pillar traceability connects all four pillars into the complete MBSE model.',notation:['Requirements pillar: 1 diagram type — Requirement Diagram (traceability and derivation).','Structure pillar: 3 diagram types — BDD (type model), IBD (instance wiring), Package (namespace).','Behavior pillar: 4 diagram types — Use Case (scope), Activity (flow), Sequence (interaction), State Machine (lifecycle).','Parametric pillar: 1 diagram type — Parametric Diagram (quantitative constraints).','Ref: OMG SysML 1.7 Specification formal/19-11-01, Table 1 — Diagram Types. https://www.omg.org/spec/SysML/1.7'],example:'Lecture 1 diagram types map to the highlighted pillar(s) in the reference card above. Connect each diagram type you produce to its pillar, and trace the cross-pillar relationships that make your model an integrated whole rather than a collection of disconnected views.',svgMarkup:`<svg viewBox="0 0 430 175" xmlns="http://www.w3.org/2000/svg" style="padding:10px;background:#1a1a1a;"><text x="215" y="15" font-family="JetBrains Mono,monospace" font-size="8" fill="#5aad7a" text-anchor="middle">OMG SysML 1.7 — 9 Diagram Types across 4 Pillars (ISO/IEC 19514:2017)</text><rect x="8" y="22" width="88" height="70" rx="4" fill="rgba(2,105,55,0.1)" stroke="#026937" stroke-width="1.3"/><text x="52" y="35" font-family="JetBrains Mono,monospace" font-size="7" fill="#026937" text-anchor="middle" font-weight="bold">REQUIREMENTS</text><rect x="14" y="42" width="76" height="16" rx="3" fill="#1a2a1a" stroke="#5aad7a" stroke-width="0.8"/><text x="52" y="54" font-family="JetBrains Mono,monospace" font-size="6.5" fill="#c5d8e8" text-anchor="middle">Requirement Diagram</text><rect x="102" y="22" width="88" height="105" rx="4" fill="rgba(2,105,55,0.1)" stroke="#026937" stroke-width="1.3"/><text x="146" y="35" font-family="JetBrains Mono,monospace" font-size="7" fill="#026937" text-anchor="middle" font-weight="bold">STRUCTURE</text><rect x="108" y="42" width="76" height="15" rx="3" fill="#1a2a1a" stroke="#5aad7a" stroke-width="0.8"/><text x="146" y="53" font-family="JetBrains Mono,monospace" font-size="6.5" fill="#c5d8e8" text-anchor="middle">Block Def. Diagram</text><rect x="108" y="61" width="76" height="15" rx="3" fill="#1a2a1a" stroke="#5aad7a" stroke-width="0.8"/><text x="146" y="72" font-family="JetBrains Mono,monospace" font-size="6.5" fill="#c5d8e8" text-anchor="middle">Internal Block Diag.</text><rect x="108" y="80" width="76" height="15" rx="3" fill="#1a2a1a" stroke="#5aad7a" stroke-width="0.8"/><text x="146" y="91" font-family="JetBrains Mono,monospace" font-size="6.5" fill="#c5d8e8" text-anchor="middle">Package Diagram</text><rect x="196" y="22" width="88" height="140" rx="4" fill="rgba(2,105,55,0.1)" stroke="#026937" stroke-width="1.3"/><text x="240" y="35" font-family="JetBrains Mono,monospace" font-size="7" fill="#026937" text-anchor="middle" font-weight="bold">BEHAVIOR</text><rect x="202" y="42" width="76" height="14" rx="3" fill="#1a2a1a" stroke="#5aad7a" stroke-width="0.8"/><text x="240" y="53" font-family="JetBrains Mono,monospace" font-size="6.5" fill="#c5d8e8" text-anchor="middle">Use Case Diagram</text><rect x="202" y="60" width="76" height="14" rx="3" fill="#1a2a1a" stroke="#5aad7a" stroke-width="0.8"/><text x="240" y="71" font-family="JetBrains Mono,monospace" font-size="6.5" fill="#c5d8e8" text-anchor="middle">Activity Diagram</text><rect x="202" y="78" width="76" height="14" rx="3" fill="#1a2a1a" stroke="#5aad7a" stroke-width="0.8"/><text x="240" y="89" font-family="JetBrains Mono,monospace" font-size="6.5" fill="#c5d8e8" text-anchor="middle">Sequence Diagram</text><rect x="202" y="96" width="76" height="14" rx="3" fill="#1a2a1a" stroke="#5aad7a" stroke-width="0.8"/><text x="240" y="107" font-family="JetBrains Mono,monospace" font-size="6.5" fill="#c5d8e8" text-anchor="middle">State Machine Diag.</text><rect x="290" y="22" width="88" height="70" rx="4" fill="rgba(201,162,39,0.08)" stroke="#C9A227" stroke-width="1.3"/><text x="334" y="35" font-family="JetBrains Mono,monospace" font-size="7" fill="#C9A227" text-anchor="middle" font-weight="bold">PARAMETRIC</text><rect x="296" y="42" width="76" height="18" rx="3" fill="#1a2a1a" stroke="#C9A227" stroke-width="0.8"/><text x="334" y="55" font-family="JetBrains Mono,monospace" font-size="6.5" fill="#c5d8e8" text-anchor="middle">Parametric Diagram</text><text x="215" y="170" font-family="JetBrains Mono,monospace" font-size="6.5" fill="#4e5668" text-anchor="middle">Ref: OMG SysML 1.7 formal/19-11-01 · ISO/IEC 19514:2017 · omg.org/spec/SysML/1.7</text></svg>`},
{category:'INCOSE Lifecycle Reference',name:'SE Lifecycle — Lecture 1 Position',diagramType:'Process Reference (informative)',shortDesc:'INCOSE SE Handbook v5 six-phase lifecycle with Lecture 1 phase highlighted. Know where you are in the lifecycle at all times.',fullDesc:'INCOSE SE Handbook v5 (2023) defines six lifecycle stages, each bounded by decision gates requiring defined model maturity. Every MBSE activity in this course maps to one or more stages. The highlighted phase shows where Lecture 1 activities fall in the lifecycle. Know the gate entry criteria — they appear on the midterm and final exam.',notation:['Highlighted phase = primary lifecycle context for Lecture 1 activities.','Phase gate = decision point requiring authority approval and defined model maturity.','MCR: Mission Concept Review; SRR: System Requirements Review; PDR: Preliminary Design Review.','CDR: Critical Design Review; TRR: Test Readiness Review; OAR: Operational Acceptance Review.','Ref: INCOSE (2023). SE Handbook v5, Section 2.3 — Systems Lifecycle Stages.'],example:'At PDR (after Lecture 7), your model must pass: derivation coverage 100%, allocation coverage 100%, no orphaned requirements, naming convention compliance 100%. These are the exact criteria evaluated in Mini Project 1.',svgMarkup:`<svg viewBox="0 0 430 98" xmlns="http://www.w3.org/2000/svg" style="padding:10px;background:#1a1a1a;"><defs><marker id="lca1" markerWidth="6" markerHeight="4" refX="5" refY="2" orient="auto"><polygon points="0 0,6 2,0 4" fill="#5aad7a"/></marker></defs><text x="215" y="15" font-family="JetBrains Mono,monospace" font-size="7.5" fill="#5aad7a" text-anchor="middle">INCOSE SE Handbook v5 — Lifecycle (L1: Concept Definition highlighted)</text><rect x="6" y="24" width="60" height="30" rx="3" fill="#1a2a1a" stroke="#C9A227" stroke-width="1.8"/><text x="36" y="44" font-family="JetBrains Mono,monospace" font-size='7.5' fill="#C9A227" text-anchor="middle" font-weight='bold'>Concept</text><rect x="76" y="24" width="60" height="30" rx="3" fill="#1a2a1a" stroke="#026937" stroke-width="1"/><text x="106" y="44" font-family="JetBrains Mono,monospace" font-size='6.5' fill="#026937" text-anchor="middle" font-weight='normal'>Sys Def</text><rect x="146" y="24" width="60" height="30" rx="3" fill="#1a2a1a" stroke="#026937" stroke-width="1"/><text x="176" y="44" font-family="JetBrains Mono,monospace" font-size='6.5' fill="#026937" text-anchor="middle" font-weight='normal'>Realization</text><rect x="216" y="24" width="60" height="30" rx="3" fill="#1a2a1a" stroke="#026937" stroke-width="1"/><text x="246" y="44" font-family="JetBrains Mono,monospace" font-size='6.5' fill="#026937" text-anchor="middle" font-weight='normal'>I&V</text><rect x="286" y="24" width="60" height="30" rx="3" fill="#1a2a1a" stroke="#026937" stroke-width="1"/><text x="316" y="44" font-family="JetBrains Mono,monospace" font-size='6.5' fill="#026937" text-anchor="middle" font-weight='normal'>Qual & Trans</text><rect x="356" y="24" width="60" height="30" rx="3" fill="#1a2a1a" stroke="#026937" stroke-width="1"/><text x="386" y="44" font-family="JetBrains Mono,monospace" font-size='6.5' fill="#026937" text-anchor="middle" font-weight='normal'>Ops & Maint</text><line x1="66" y1="39" x2="76" y2="39" stroke="#5aad7a" stroke-width="1" marker-end="url(#lca1)"/><line x1="136" y1="39" x2="146" y2="39" stroke="#5aad7a" stroke-width="1" marker-end="url(#lca1)"/><line x1="206" y1="39" x2="216" y2="39" stroke="#5aad7a" stroke-width="1" marker-end="url(#lca1)"/><line x1="276" y1="39" x2="286" y2="39" stroke="#5aad7a" stroke-width="1" marker-end="url(#lca1)"/><line x1="346" y1="39" x2="356" y2="39" stroke="#5aad7a" stroke-width="1" marker-end="url(#lca1)"/><polygon points="66,55 72,62 66,69 60,62" fill="#0d1a0d" stroke="#C9A227" stroke-width="1"/><text x="66" y="80" font-family="JetBrains Mono,monospace" font-size="6" fill="#C9A227" text-anchor="middle">MCR</text><polygon points="136,55 142,62 136,69 130,62" fill="#0d1a0d" stroke="#C9A227" stroke-width="1"/><text x="136" y="80" font-family="JetBrains Mono,monospace" font-size="6" fill="#C9A227" text-anchor="middle">SRR/PDR</text><polygon points="206,55 212,62 206,69 200,62" fill="#0d1a0d" stroke="#C9A227" stroke-width="1"/><text x="206" y="80" font-family="JetBrains Mono,monospace" font-size="6" fill="#C9A227" text-anchor="middle">CDR</text><polygon points="276,55 282,62 276,69 270,62" fill="#0d1a0d" stroke="#C9A227" stroke-width="1"/><text x="276" y="80" font-family="JetBrains Mono,monospace" font-size="6" fill="#C9A227" text-anchor="middle">TRR</text><polygon points="346,55 352,62 346,69 340,62" fill="#0d1a0d" stroke="#C9A227" stroke-width="1"/><text x="346" y="80" font-family="JetBrains Mono,monospace" font-size="6" fill="#C9A227" text-anchor="middle">OAR</text><text x="215" y="95" font-family="JetBrains Mono,monospace" font-size="6.5" fill="#4e5668" text-anchor="middle">Ref: INCOSE (2023). SE Handbook v5, Section 2.3 — Systems Lifecycle Stages</text></svg>`}
  ],
        example: 'In the eVTOL sizing model, the top-level block «block» eVTOL_AirTaxi owns part properties: propulsionSystem: PropulsionSystem [1], batterySystem: BatterySystem [1], structuralAirframe: Airframe [1], and avionics: AvionicsSystem [1]. The BDD makes the system decomposition explicit, unambiguous, and machine-traversable — enabling automated impact analysis when any sub-block property changes.',
        svgMarkup: `<svg viewBox="0 0 420 220" xmlns="http://www.w3.org/2000/svg" style="padding:16px;">
          <defs>
            <style>
              .blk-rect { fill: #161d2b; stroke: #026937; stroke-width: 1.8; rx: 4; }
              .blk-hdr  { fill: rgba(2,105,55,0.25); }
              .blk-txt  { font-family: 'JetBrains Mono', monospace; font-size: 11px; fill: #c5d8e8; }
              .blk-kw   { font-family: 'JetBrains Mono', monospace; font-size: 9px; fill: #5aad7a; }
              .blk-prop { font-family: 'JetBrains Mono', monospace; font-size: 9.5px; fill: #7a9ab4; }
              .conn-line { stroke: #D4AF37; stroke-width: 1.5; fill: none; }
              .diamond  { fill: #026937; stroke: #5aad7a; stroke-width: 1; }
            </style>
          </defs>
          <!-- Parent block -->
          <rect x="140" y="10" width="140" height="80" rx="3" class="blk-rect"/>
          <rect x="140" y="10" width="140" height="24" rx="3" class="blk-hdr"/>
          <rect x="140" y="32" width="140" height="2" style="fill:rgba(2,105,55,0.3)"/>
          <text x="210" y="26" text-anchor="middle" class="blk-kw">«block»</text>
          <text x="210" y="48" text-anchor="middle" class="blk-txt" font-weight="bold">eVTOL_AirTaxi</text>
          <text x="150" y="64" class="blk-prop">+ MTOW: kg</text>
          <text x="150" y="77" class="blk-prop">+ crewCount: Integer</text>
          <!-- Child block left -->
          <rect x="20" y="140" width="130" height="68" rx="3" class="blk-rect"/>
          <rect x="20" y="140" width="130" height="22" rx="3" class="blk-hdr"/>
          <text x="85" y="155" text-anchor="middle" class="blk-kw">«block»</text>
          <text x="85" y="170" text-anchor="middle" class="blk-txt" font-weight="bold">BatterySystem</text>
          <text x="29" y="183" class="blk-prop">+ capacity: kWh</text>
          <text x="29" y="196" class="blk-prop">+ mass: kg</text>
          <!-- Child block right -->
          <rect x="270" y="140" width="130" height="68" rx="3" class="blk-rect"/>
          <rect x="270" y="140" width="130" height="22" rx="3" class="blk-hdr"/>
          <text x="335" y="155" text-anchor="middle" class="blk-kw">«block»</text>
          <text x="335" y="170" text-anchor="middle" class="blk-txt" font-weight="bold">Airframe</text>
          <text x="279" y="183" class="blk-prop">+ structMass: kg</text>
          <text x="279" y="196" class="blk-prop">+ material: String</text>
          <!-- Composition lines -->
          <line x1="85" y1="140" x2="170" y2="90" class="conn-line"/>
          <polygon points="167,84 173,90 163,92" class="diamond"/>
          <line x1="335" y1="140" x2="250" y2="90" class="conn-line"/>
          <polygon points="247,84 253,90 243,92" class="diamond"/>
          <!-- Labels -->
          <text x="112" y="124" class="blk-kw" fill="#D4AF37">1</text>
          <text x="252" y="124" class="blk-kw" fill="#D4AF37">1</text>
        </svg>`,
      },

      {
        category: 'SysML Core Construct',
        name: 'Requirement',
        diagramType: 'Requirement Diagram',
        shortDesc: 'Captures a stakeholder need or system requirement as a first-class model element with traceability relationships.',
        fullDesc: 'In SysML 1.7, a Requirement is a stereotype of NamedElement that captures a capability or condition that the system must satisfy. Unlike a row in a spreadsheet, a SysML requirement is a model element with formal properties (id, text, priority, risk, verificationMethod) and formal relationships (derive, refine, trace, satisfy, verify, containment). Requirements diagrams show hierarchical requirement breakdowns and the relationships between requirements and the design elements that address them.',
        notation: [
          'Shown as a rectangle with «requirement» stereotype in the header.',
          'Mandatory properties: id (unique identifier string) and text (requirement statement).',
          'Optional properties: priority, risk, verificationMethod.',
          'containment (nesting): requirement A contains sub-requirement B when B is part of A\'s hierarchy.',
          'satisfy: a design block «satisfies» a requirement when it provides the required capability.',
          'verify: a test case «verifies» a requirement when it provides objective evidence of compliance.',
          'derive: requirement B is «derived» from requirement A when B is a logical consequence of A.',
        ],
        example: 'For the eVTOL system, a top-level requirement REQ-001 (text: "The system shall achieve an MTOW not exceeding 3,200 kg under the MBSE-parametric sizing model") is derived from stakeholder need STK-001. A derived requirement REQ-001.1 (text: "The battery system shall not exceed 650 kg mass to remain within the MTOW allocation") is then satisfied by the BatterySystem block in the BDD, and verified by the WeightBuildUpAnalysis test case.',
        svgMarkup: `<svg viewBox="0 0 420 190" xmlns="http://www.w3.org/2000/svg" style="padding:16px;">
          <defs>
            <style>
              .req-rect { fill: #1a2235; stroke: #026937; stroke-width: 1.5; }
              .req-hdr  { fill: rgba(2,105,55,0.2); }
              .req-kw   { font-family:'JetBrains Mono',monospace; font-size:9px; fill:#5aad7a; }
              .req-id   { font-family:'JetBrains Mono',monospace; font-size:9px; fill:#D4AF37; }
              .req-txt  { font-family:'JetBrains Mono',monospace; font-size:8.5px; fill:#9ab5c8; }
              .rel-line { stroke:#5aad7a; stroke-width:1.2; stroke-dasharray:5,3; fill:none; }
              .rel-lbl  { font-family:'JetBrains Mono',monospace; font-size:8px; fill:#5aad7a; }
            </style>
          </defs>
          <!-- Parent requirement -->
          <rect x="130" y="8" width="160" height="66" rx="3" class="req-rect"/>
          <rect x="130" y="8" width="160" height="20" rx="3" class="req-hdr"/>
          <text x="210" y="22" text-anchor="middle" class="req-kw">«requirement»</text>
          <text x="137" y="38" class="req-id">id = REQ-001</text>
          <text x="137" y="50" class="req-txt">The system shall achieve</text>
          <text x="137" y="61" class="req-txt">MTOW ≤ 3,200 kg [MBSE]</text>
          <!-- Child requirement 1 -->
          <rect x="10" y="120" width="160" height="58" rx="3" class="req-rect"/>
          <rect x="10" y="120" width="160" height="20" rx="3" class="req-hdr"/>
          <text x="90" y="133" text-anchor="middle" class="req-kw">«requirement»</text>
          <text x="17" y="149" class="req-id">id = REQ-001.1</text>
          <text x="17" y="161" class="req-txt">Battery mass ≤ 650 kg</text>
          <text x="17" y="172" class="req-txt">allocated to BatterySystem</text>
          <!-- Child requirement 2 -->
          <rect x="250" y="120" width="155" height="58" rx="3" class="req-rect"/>
          <rect x="250" y="120" width="155" height="20" rx="3" class="req-hdr"/>
          <text x="327" y="133" text-anchor="middle" class="req-kw">«requirement»</text>
          <text x="257" y="149" class="req-id">id = REQ-001.2</text>
          <text x="257" y="161" class="req-txt">Hover endurance ≥ 5 min</text>
          <text x="257" y="172" class="req-txt">at 115% rated power</text>
          <!-- Containment lines -->
          <line x1="90" y1="120" x2="175" y2="74" class="rel-line"/>
          <text x="105" y="104" class="rel-lbl">«containment»</text>
          <line x1="327" y1="120" x2="245" y2="74" class="rel-line"/>
        </svg>`,
      },

      {
        category: 'SysML Core Construct',
        name: 'System Context (Use Case)',
        diagramType: 'Use Case Diagram',
        shortDesc: 'Defines the system boundary and describes externally visible system services from the stakeholder perspective.',
        fullDesc: 'A Use Case Diagram in SysML 1.7 describes the system of interest from an external perspective — what services it provides to which stakeholders. It is the entry point for operational context definition. The system boundary rectangle separates the system of interest from its operational environment. Actors represent external entities (humans, organizations, or other systems) that interact with the system. Use cases are named behaviors or goals that the system can achieve for an actor. Relationships include association (participation), include (mandatory reuse), extend (optional/conditional extension), and generalization (specialization among actors or use cases).',
        notation: [
          'System boundary: a labeled rectangle enclosing all use cases.',
          'Actor: a stick figure (human actor) or a rectangle with «actor» stereotype (system actor).',
          'Use case: an ellipse with the use case name inside.',
          'Association: a solid line between actor and use case (no arrowhead implies bidirectional participation).',
          '«include»: dashed arrow pointing from the base use case to the included use case (mandatory behavior).',
          '«extend»: dashed arrow pointing from the extension use case to the base use case (optional behavior).',
          'Generalization: solid line with hollow triangle from specialized to general actor or use case.',
        ],
        example: 'For the Mars Rover system context, actors include Mission Scientist (primary), Surface Operations Controller (primary), NASA Mission Director (regulatory/oversight), and Deep Space Network (supporting system). Use cases include Traverse Terrain, Acquire Scientific Sample, Transmit Telemetry, Execute Autonomous Navigation, and Execute Safe Mode. «include» from Traverse Terrain to Execute Autonomous Navigation captures the mandatory dependency on the navigation subsystem for all surface operations.',
        svgMarkup: `<svg viewBox="0 0 420 200" xmlns="http://www.w3.org/2000/svg" style="padding:12px;">
          <defs>
            <style>
              .uc-boundary { fill:rgba(2,105,55,0.05); stroke:#026937; stroke-width:1.5; stroke-dasharray:6,3; }
              .uc-ellipse  { fill:#1a2235; stroke:#5aad7a; stroke-width:1.3; }
              .uc-actor    { stroke:#D4AF37; stroke-width:1.4; fill:none; }
              .uc-txt      { font-family:'JetBrains Mono',monospace; font-size:8.5px; fill:#9ab5c8; text-anchor:middle; }
              .uc-hdr      { font-family:'JetBrains Mono',monospace; font-size:9px; fill:#5aad7a; }
              .uc-line     { stroke:#7a9ab4; stroke-width:1.1; stroke-dasharray:4,2; fill:none; }
              .uc-solid    { stroke:#7a9ab4; stroke-width:1.1; fill:none; }
            </style>
          </defs>
          <!-- System boundary -->
          <rect x="90" y="14" width="240" height="168" rx="6" class="uc-boundary"/>
          <text x="210" y="30" text-anchor="middle" class="uc-hdr">Mars Rover System</text>
          <!-- Use cases -->
          <ellipse cx="210" cy="65" rx="54" ry="18" class="uc-ellipse"/>
          <text x="210" y="69" class="uc-txt">Traverse Terrain</text>
          <ellipse cx="210" cy="110" rx="58" ry="18" class="uc-ellipse"/>
          <text x="210" y="114" class="uc-txt">Acquire Scientific Sample</text>
          <ellipse cx="210" cy="158" rx="52" ry="16" class="uc-ellipse"/>
          <text x="210" y="162" class="uc-txt">Execute Safe Mode</text>
          <!-- Actor: Mission Scientist -->
          <circle cx="30" cy="72" r="9" class="uc-actor"/>
          <line x1="30" y1="81" x2="30" y2="105" class="uc-actor"/>
          <line x1="30" y1="88" x2="16" y2="98" class="uc-actor"/>
          <line x1="30" y1="88" x2="44" y2="98" class="uc-actor"/>
          <line x1="30" y1="105" x2="18" y2="118" class="uc-actor"/>
          <line x1="30" y1="105" x2="42" y2="118" class="uc-actor"/>
          <text x="30" y="130" text-anchor="middle" class="uc-txt" style="fill:#D4AF37;">Mission Scientist</text>
          <!-- Actor: Ops Controller -->
          <circle cx="390" cy="72" r="9" class="uc-actor"/>
          <line x1="390" y1="81" x2="390" y2="105" class="uc-actor"/>
          <line x1="390" y1="88" x2="376" y2="98" class="uc-actor"/>
          <line x1="390" y1="88" x2="404" y2="98" class="uc-actor"/>
          <line x1="390" y1="105" x2="378" y2="118" class="uc-actor"/>
          <line x1="390" y1="105" x2="402" y2="118" class="uc-actor"/>
          <text x="390" y="130" text-anchor="middle" class="uc-txt" style="fill:#D4AF37;">Ops Controller</text>
          <!-- Association lines -->
          <line x1="42" y1="80" x2="156" y2="66" class="uc-solid"/>
          <line x1="42" y1="88" x2="152" y2="108" class="uc-solid"/>
          <line x1="376" y1="80" x2="264" y2="66" class="uc-solid"/>
          <line x1="376" y1="95" x2="268" y2="110" class="uc-solid"/>
          <line x1="376" y1="108" x2="262" y2="155" class="uc-solid"/>
          <!-- include dependency -->
          <line x1="210" y1="83" x2="210" y2="92" class="uc-line"/>
          <text x="216" y="100" class="uc-txt" style="fill:#5aad7a;">«include»</text>
        </svg>`,
      },

      {
        category: 'SysML Core Construct',
        name: 'Internal Block Diagram',
        diagramType: 'Internal Block Diagram (IBD)',
        shortDesc: 'Reveals the instance-level internal architecture: parts, ports, connectors, and item flows within a block.',
        fullDesc: 'Where the BDD shows types and classifications, the Internal Block Diagram (IBD) shows instances: the actual parts assembled within a specific block context, connected through ports by connectors, with item flows showing what flows across each interface. IBDs are the primary instrument for interface definition and interface control in MBSE workflows. Each part in an IBD is a usage of a block defined in the BDD. Ports define interface points; item flows declare what kind of energy, data, or material crosses each interface.',
        notation: [
          'Framed by a rectangle labeled with the context block name in the top-left corner.',
          'Parts: rectangles inside the frame, labeled as partName:BlockType.',
          'Proxy ports (rectangular attachment point on block boundary) represent interface definitions from the block\'s type.',
          'Full ports (small filled rectangle) expose complete interface block instances.',
          'Connectors: lines between port-pairs showing authorized interactions.',
          'Item flow arrows on connectors declare what flows across the connector (e.g., «flow» electricPower).',
          'The IBD does not show type-level relationships (those belong in the BDD); it shows instance-level wiring.',
        ],
        example: 'Within the eVTOL_AirTaxi IBD, part battSys:BatterySystem connects to part propSys:PropulsionSystem via a connector between their power ports, with an item flow «flow» DCPower [700V, ≤400A]. Part avionics:AvionicsSystem connects to propSys via a CANBUS data port, with item flow «flow» ThrustCommand [CAN FD frame]. This IBD is the authoritative interface control document for the vehicle-level power and data architecture.',
        svgMarkup: `<svg viewBox="0 0 420 200" xmlns="http://www.w3.org/2000/svg" style="padding:12px;">
          <defs>
            <style>
              .ibd-frame { fill:rgba(2,105,55,0.03); stroke:#026937; stroke-width:1.5; }
              .ibd-part  { fill:#161d2b; stroke:#5aad7a; stroke-width:1.2; }
              .ibd-port  { fill:#026937; stroke:#5aad7a; stroke-width:1; }
              .ibd-conn  { stroke:#D4AF37; stroke-width:1.3; stroke-dasharray:4,2; fill:none; }
              .ibd-flow  { stroke:#D4AF37; stroke-width:1; fill:none; marker-end:url(#ibd-arrow); }
              .ibd-txt   { font-family:'JetBrains Mono',monospace; font-size:9px; fill:#9ab5c8; text-anchor:middle; }
              .ibd-kw    { font-family:'JetBrains Mono',monospace; font-size:8px; fill:#5aad7a; text-anchor:middle; }
              .ibd-flow-lbl { font-family:'JetBrains Mono',monospace; font-size:7.5px; fill:#D4AF37; }
            </style>
            <marker id="ibd-arrow" markerWidth="7" markerHeight="5" refX="6" refY="2.5" orient="auto">
              <polygon points="0 0, 7 2.5, 0 5" fill="#D4AF37"/>
            </marker>
          </defs>
          <!-- Context frame -->
          <rect x="8" y="10" width="404" height="178" rx="5" class="ibd-frame"/>
          <text x="16" y="26" style="font-family:'JetBrains Mono',monospace;font-size:9px;fill:#5aad7a;">«block» eVTOL_AirTaxi [internal block diagram]</text>
          <!-- BatterySystem part -->
          <rect x="22" y="40" width="118" height="80" rx="3" class="ibd-part"/>
          <text x="81" y="56" class="ibd-kw">battSys:</text>
          <text x="81" y="69" class="ibd-txt" font-weight="bold">BatterySystem</text>
          <text x="81" y="83" class="ibd-kw" style="fill:#7a9ab4;">cap=90kWh</text>
          <text x="81" y="96" class="ibd-kw" style="fill:#7a9ab4;">mass=580kg</text>
          <!-- BatterySystem power port -->
          <rect x="137" y="72" width="8" height="12" rx="1" class="ibd-port"/>
          <!-- PropulsionSystem part -->
          <rect x="160" y="40" width="100" height="80" rx="3" class="ibd-part"/>
          <text x="210" y="58" class="ibd-kw">propSys:</text>
          <text x="210" y="72" class="ibd-txt" font-weight="bold">Propulsion</text>
          <text x="210" y="86" class="ibd-kw" style="fill:#7a9ab4;">rotors: 6</text>
          <text x="210" y="99" class="ibd-kw" style="fill:#7a9ab4;">P_rated=280kW</text>
          <!-- PropSys input port -->
          <rect x="155" y="72" width="8" height="12" rx="1" class="ibd-port"/>
          <!-- Power connector -->
          <line x1="145" y1="78" x2="155" y2="78" class="ibd-conn"/>
          <text x="150" y="71" class="ibd-flow-lbl">DCPower</text>
          <!-- AvionicsSystem part -->
          <rect x="288" y="40" width="110" height="80" rx="3" class="ibd-part"/>
          <text x="343" y="58" class="ibd-kw">avionics:</text>
          <text x="343" y="72" class="ibd-txt" font-weight="bold">Avionics</text>
          <text x="343" y="86" class="ibd-kw" style="fill:#7a9ab4;">protocol: CAN FD</text>
          <!-- Avionics output port -->
          <rect x="283" y="72" width="8" height="12" rx="1" class="ibd-port"/>
          <!-- Propulsion input port (right side) -->
          <rect x="257" y="72" width="8" height="12" rx="1" class="ibd-port"/>
          <!-- Data connector -->
          <line x1="283" y1="78" x2="265" y2="78" class="ibd-conn"/>
          <text x="274" y="71" class="ibd-flow-lbl">ThrustCmd</text>
          <!-- Item flow arrows -->
          <path d="M 150 78 L 150 150 L 210 150 L 210 120" class="ibd-conn" style="stroke:#D4AF37;stroke-width:1;"/>
          <text x="174" y="163" class="ibd-flow-lbl">«flow» DCPower [700VDC]</text>
        </svg>`,
      },

      {
        category: 'SysML Core Construct',
        name: 'Parametric Diagram',
        diagramType: 'Parametric Diagram',
        shortDesc: 'Encodes engineering equations as constraint blocks and binds them to system properties, enabling quantitative analysis.',
        fullDesc: 'The Parametric Diagram is the distinguishing analytical pillar of SysML that elevates it beyond any purely structural or behavioral modeling language. A constraint block encodes an engineering equation as a named element with parameters; binding connectors wire those parameters to value properties in the structural model. When a bound value changes — for example, battery cell energy density updates due to a supplier revision — the parametric solver propagates the change through all connected constraint blocks and recomputes all affected system metrics automatically. This is the mechanism that prevents the eVTOL MTOW underestimation described in Section 2.',
        notation: [
          'Constraint block: a rectangle with «constraint» stereotype, containing the equation as a constraint property.',
          'Constraint parameter: a port-like element on the boundary of the constraint block, named and typed.',
          'Binding connector: a solid line connecting a constraint parameter to a value property in the system structure. Semantics: the two ends are always equal.',
          'The parametric diagram frame is labeled with the owning block name and «parametric» keyword.',
          'Constraint blocks are typically chained: the output parameter of one constraint feeds the input parameter of another, forming an equation network.',
        ],
        example: 'MTOW Parametric Network: ConstraintBlock HoverPowerCalc encodes P_hover = MTOW × g × (1/FM) × sqrt(MTOW×g / (2ρA_disk)). Its MTOW parameter is bound to the MTOW value property of the eVTOL_AirTaxi block. ConstraintBlock BatterySizing encodes m_batt = (E_hover × SF_hover + E_cruise × SF_cruise) / (e_cell × η_disch). Its m_batt output parameter is bound back to the BatterySystem.mass value property, which rolls up into the MTOW constraint through MassRollupCalc. The circular dependency converges iteratively to MTOW = 2,969 kg.',
        svgMarkup: `<svg viewBox="0 0 420 195" xmlns="http://www.w3.org/2000/svg" style="padding:12px;">
          <defs>
            <style>
              .par-frame { fill:rgba(2,105,55,0.03); stroke:#026937; stroke-width:1.5; }
              .par-cblock { fill:#1a2235; stroke:#D4AF37; stroke-width:1.3; }
              .par-cbhdr  { fill:rgba(212,175,55,0.12); }
              .par-param  { fill:#026937; stroke:#5aad7a; stroke-width:1; }
              .par-bind   { stroke:#5aad7a; stroke-width:1.2; fill:none; }
              .par-txt    { font-family:'JetBrains Mono',monospace; font-size:8.5px; fill:#9ab5c8; text-anchor:middle; }
              .par-kw     { font-family:'JetBrains Mono',monospace; font-size:8px; fill:#D4AF37; text-anchor:middle; }
              .par-eq     { font-family:'JetBrains Mono',monospace; font-size:7.5px; fill:#7dba97; }
            </style>
          </defs>
          <!-- Frame -->
          <rect x="8" y="10" width="404" height="175" rx="5" class="par-frame"/>
          <text x="16" y="26" style="font-family:'JetBrains Mono',monospace;font-size:9px;fill:#D4AF37;">eVTOL_AirTaxi [parametric]</text>
          <!-- HoverPowerCalc constraint block -->
          <rect x="22" y="38" width="130" height="70" rx="3" class="par-cblock"/>
          <rect x="22" y="38" width="130" height="20" rx="3" class="par-cbhdr"/>
          <text x="87" y="52" class="par-kw">«constraint»</text>
          <text x="87" y="65" class="par-txt" font-weight="bold">HoverPowerCalc</text>
          <text x="30" y="79" class="par-eq">{ P = MTOW·g/FM</text>
          <text x="30" y="91" class="par-eq">  · √(MTOW·g/2ρA) }</text>
          <!-- BatterySizing constraint block -->
          <rect x="290" y="38" width="118" height="70" rx="3" class="par-cblock"/>
          <rect x="290" y="38" width="118" height="20" rx="3" class="par-cbhdr"/>
          <text x="349" y="52" class="par-kw">«constraint»</text>
          <text x="349" y="65" class="par-txt" font-weight="bold">BatterySizing</text>
          <text x="298" y="79" class="par-eq">{ m_batt = E_req</text>
          <text x="298" y="91" class="par-eq">  / (e·η) }</text>
          <!-- MassRollup constraint block -->
          <rect x="155" y="120" width="110" height="52" rx="3" class="par-cblock"/>
          <rect x="155" y="120" width="110" height="18" rx="3" class="par-cbhdr"/>
          <text x="210" y="132" class="par-kw">«constraint»</text>
          <text x="210" y="147" class="par-txt" font-weight="bold">MassRollup</text>
          <text x="162" y="162" class="par-eq">{ MTOW = Σ m_i + OEW }</text>
          <!-- Parameters (small port squares) -->
          <rect x="147" y="64" width="8" height="10" rx="1" class="par-param"/>
          <rect x="284" y="64" width="8" height="10" rx="1" class="par-param"/>
          <rect x="202" y="169" width="10" height="8" rx="1" class="par-param"/>
          <!-- Binding connectors -->
          <path d="M 87 108 Q 87 130 155 145" class="par-bind" stroke-dasharray="4,2"/>
          <path d="M 349 108 Q 349 130 265 145" class="par-bind" stroke-dasharray="4,2"/>
          <path d="M 155 144 L 80 144 L 80 68 L 147 68" class="par-bind"/>
          <path d="M 265 144 L 332 144 L 332 68 L 292 68" class="par-bind"/>
          <!-- MTOW label -->
          <text x="100" y="75" class="par-eq" style="fill:#D4AF37;">MTOW</text>
          <text x="295" y="75" class="par-eq" style="fill:#D4AF37;">E_req</text>
          <text x="163" y="140" class="par-eq" style="fill:#D4AF37;">→2,969 kg</text>
        </svg>`,
      },
    ],

    /* ═══════════════════════════════════════════════════════════════
       PLAYGROUND  ─  Tab 3 interactive SysML canvas config
       ═══════════════════════════════════════════════════════════════ */
    playground: {
      title:        'System Context Modeling — System & Stakeholder Blocks',
      instructions: 'This mini-project introduces the first SysML building block: connecting a System Context block to a Stakeholder block using an association. Use the palette buttons to add blocks, then click the green port circle on any block to begin a connection. Click a destination block to complete the connection. Drag blocks to reposition them.',
      objectives: [
        'Add a «block» SystemContext element representing the Mars Rover operational environment.',
        'Add a «block» Stakeholder element for each stakeholder class (Mission Scientist, Ops Controller).',
        'Connect each Stakeholder block to the SystemContext block using an association relationship.',
        'Observe that the connection models a stakeholder-system boundary interaction, not an internal interface.',
      ],
      palette: [
        { stereotype: '«block»',       name: 'SystemContext',       props: ['+ name: String', '+ missionDomain: String'] },
        { stereotype: '«block»',       name: 'Stakeholder',         props: ['+ role: String', '+ concern: String'] },
        { stereotype: '«block»',       name: 'MarsRoverSOI',        props: ['+ MTOW: kg', '+ powerBudget: W'] },
        { stereotype: '«actor»',       name: 'MissionScientist',    props: ['+ affiliation: String'] },
        { stereotype: '«actor»',       name: 'OpsController',       props: ['+ certLevel: String'] },
        { stereotype: '«requirement»', name: 'REQ-001',             props: ['+ id = REQ-001', '+ text = MTOW ≤ 3200 kg'] },
      ],
      defaultBlocks: [
        { stereotype: '«block»', name: 'SystemContext',    props: ['+ name: String', '+ missionDomain: String'],  x: 30,  y: 60 },
        { stereotype: '«actor»', name: 'MissionScientist', props: ['+ affiliation: String'],                      x: 30,  y: 230 },
        { stereotype: '«actor»', name: 'OpsController',    props: ['+ certLevel: String'],                        x: 240, y: 230 },
      ],
    },

    /* ═══════════════════════════════════════════════════════════════
       QUIZ  ─  Tab 4 knowledge check
       ═══════════════════════════════════════════════════════════════ */
    quiz: {
      questions: [
        {
          question: 'The INCOSE SE Handbook v5 defines a system as a combination of interacting elements organized to achieve a stated purpose. What term describes the properties of the whole that cannot be attributed to any single constituent part in isolation?',
          options: [
            'Aggregative behavior',
            'Emergent behavior',
            'Functional decomposition',
            'Modular behavior',
          ],
          correct: 1,
          explanation: 'Emergent behavior refers to system-level properties and behaviors that arise from the interaction of components and cannot be predicted from examining any single part in isolation. This is the defining challenge that drives the need for integrated, model-based engineering rather than component-level analysis.',
        },
        {
          question: 'A static spreadsheet-based sizing model incorrectly estimates the MTOW of an eVTOL air-taxi at 1,722 kg. The MBSE parametric model accounts for the hover-reserve battery mass and the iterative weight snowball effect. What MTOW does the parametric model correctly compute, representing a 72.4% underestimation by the document-centric approach?',
          options: [
            '1,980 kg',
            '2,450 kg',
            '2,969 kg',
            '3,200 kg',
          ],
          correct: 2,
          explanation: 'The parametric model\'s iterative solution converges at 2,969 kg once the hover-reserve battery mass (31% larger than cruise-only sizing), additional structural mass, and resultant power demand increase are properly propagated through binding connectors in the SysML parametric diagram. This represents a 72.4% underestimation by the document-centric method — a safety-critical error for any airworthiness program.',
        },
        {
          question: 'Which of the following correctly identifies the four pillars of OMG SysML 1.7?',
          options: [
            'Class diagrams, Sequence diagrams, Component diagrams, and Deployment diagrams',
            'Requirements, Structure, Behavior, and Parametric diagrams',
            'Functional flow, Data flow, Control flow, and Interface definitions',
            'Use cases, Activities, State machines, and Collaboration diagrams',
          ],
          correct: 1,
          explanation: 'SysML 1.7 organizes its nine diagram types across four pillars: (1) Requirements — capturing stakeholder needs and traceability; (2) Structure — BDD and IBD for system composition and interfaces; (3) Behavior — activity, sequence, state machine, and use case diagrams; and (4) Parametric — encoding engineering constraint equations and supporting quantitative trade studies.',
        },
        {
          question: 'In SysML 1.7, a Parametric Diagram uses binding connectors to wire constraint block parameters to value properties in the structural model. What is the precise semantic meaning of a binding connector?',
          options: [
            'The connected elements have a dependency relationship — one must be updated when the other changes.',
            'The two connected ends always hold the same value — they are instantaneously equal and co-assigned.',
            'The connected elements share the same type but may hold different values at runtime.',
            'The connection represents a physical wiring or data bus between components.',
          ],
          correct: 1,
          explanation: 'A binding connector in SysML 1.7 has identity semantics: the two feature values it connects are constrained to be equal at all times. This is stronger than a dependency relationship. It is the formal mechanism that propagates a change in battery mass through the power constraint to the hover power calculation to the MTOW rollup — the computational chain that prevents the weight-snowball underestimation.',
        },
        {
          question: 'According to the INCOSE taxonomy, which of the following is the most complete characterization of "stakeholder" for the purpose of systems engineering and stakeholder needs analysis?',
          options: [
            'The paying customer who funds the development program.',
            'The end user who physically operates the system in its operational environment.',
            'Any individual, organization, or system with an interest in the performance, operation, or outcome of the system of interest — including users, operators, maintainers, regulatory bodies, and supporting systems.',
            'The program manager and lead systems engineer responsible for the design baseline.',
          ],
          correct: 2,
          explanation: 'INCOSE\'s stakeholder definition is deliberately broad: it encompasses primary users, secondary users affected by the system\'s operation, regulatory authorities who impose safety and environmental constraints, maintainers who service the system across its lifecycle, and even supporting systems with operational dependencies. This comprehensive framing is essential because requirements omission errors — often caused by ignoring non-primary stakeholders — are among the most expensive defects to correct once a design is baselined.',
        },
      ],
    },

    /* ═══════════════════════════════════════════════════════════════
       ASSIGNMENT  ─  Tab 5 rubric & challenge
       ═══════════════════════════════════════════════════════════════ */
    assignment: {
      title:  'Assignment 1: Operational Context & Stakeholder Analysis — Autonomous Mars Rover',
      brief:  'You are the lead systems engineer for the Autonomous Mars Rover program. Your task is to define the complete operational context and primary stakeholder taxonomy for the rover system, develop a minimum of 15 verifiable candidate system-level requirements written in clear "shall" language, and produce a structured argument for your system boundary decision. This assignment assesses your ability to translate raw operational context into a rigorous MBSE foundation before any architectural modeling begins. All work must be submitted as a structured report (PDF) with evidence sections mapped to each rubric criterion.',
      deliverables: [
        'Stakeholder Taxonomy Table: Identify a minimum of 6 distinct stakeholder classes. For each, state role, primary concern, level of authority over requirements, and interface type with the system of interest.',
        'System Context Narrative: Define the operational boundary of the Mars Rover SOI. Identify at least 4 external systems (enabling systems, interfacing systems, and environmental actors). Justify all boundary decisions in writing.',
        'Mission Thread Description: Describe the primary operational mission thread for a nominal science traverse (surface navigation → sample acquisition → data uplink) identifying inputs, outputs, preconditions, and success criteria.',
        'Candidate Requirements List: Write a minimum of 15 system-level requirements in "The system shall…" format. Each requirement must be atomic, verifiable, and tagged with: ID, source stakeholder, verification method (Analysis/Test/Inspection/Demonstration), and priority (High/Medium/Low).',
        'eVTOL Analogy Reflection: In 200–300 words, explain why the MTOW underestimation case study from Lecture 1 is directly relevant to Mars rover system architecture decisions — specifically, identify an analogous iterative coupling in the rover design that a document-centric approach could fail to capture.',
      ],
      rubric: [
        {
          criterion: 'Requirements Quality',
          descriptor: 'Clarity, atomicity, verifiability, completeness, and "shall" language discipline.',
          max: 25,
        },
        {
          criterion: 'Stakeholder Taxonomy Depth',
          descriptor: 'Identification of ≥6 stakeholder classes, concern mapping, and authority level.',
          max: 20,
        },
        {
          criterion: 'System Boundary & Context Reasoning',
          descriptor: 'Logical justification of SOI boundary, ≥4 external actors/systems identified.',
          max: 20,
        },
        {
          criterion: 'Mission Thread Coherence',
          descriptor: 'Completeness of nominal science traverse thread: inputs, outputs, success criteria.',
          max: 15,
        },
        {
          criterion: 'MBSE Parametric Analogy Reflection',
          descriptor: 'Quality of connection between eVTOL snowball case and rover iterative coupling.',
          max: 10,
        },
        {
          criterion: 'Professional Presentation & Structure',
          descriptor: 'Document formatting, traceability tags, naming conventions, oral readiness.',
          max: 10,
        },
      ],
      gradingNotes: [
        'A requirement written as "The system should be reliable" earns zero points on the Requirements Quality criterion — it is neither atomic, verifiable, nor in proper "shall" language.',
        'Stakeholders must include both technical and non-technical classes. Missing regulatory bodies (e.g., NASA Office of Safety and Mission Assurance) or environmental actors (e.g., Martian atmosphere as an operating context constraint) will limit the Stakeholder Taxonomy score to "Developing" level.',
        'The mission thread must specify the autonomous navigation decision loop explicitly. An entry that describes only nominal traverse without an obstacle avoidance or communication blackout scenario cannot score above 10/15 on Mission Thread Coherence.',
        'The eVTOL analogy reflection is graded on depth of technical insight, not length. The best responses identify a specific mass–power–thermal coupling in the rover (e.g., radioisotope thermoelectric generator (RTG) thermal load affecting battery operating temperature affecting available power affecting mobility range) and explain how a parametric binding connector would propagate this dependency.',
        'Late submissions receive a 10-point deduction per calendar day. No submissions are accepted after five calendar days past the due date.',
      ],
    },

  
    courseMeta:{courseCode:'CEG/EGR 7800',courseTitle:'Model-Based Systems Engineering',university:'Wright State University',college:'College of Engineering and Computer Science',totalPoints:300,gradeBreakdown:{weeklyAssignments:{points:150,pct:50,desc:'30 weekly assignments x 5 pts each'},weeklyMCQ:{points:30,pct:10,desc:'30 quizzes x 5 Qs x 1 pt (auto-graded, closes Sunday 11:59 PM)'},miniProject1:{points:30,pct:10,desc:'AWRF Requirements and Architecture (due end of Week 8)'},miniProject2:{points:30,pct:10,desc:'eVTOL Parametric Sizing Study (due end of Week 17)'},midtermExam:{points:30,pct:10,desc:'Week 15 open-note exam covering Lectures 1-14 (90 minutes)'},finalProject:{points:60,pct:20,desc:'Capstone Portfolio Defense Week 30 — 3 track options: AWRF Track A, eVTOL Track B, CubeSat Track C'}},gradeScale:{A:'270-300 (90-100%)',B:'240-269 (80-89%)',C:'210-239 (70-79%)',D:'180-209 (60-69%)',F:'below 180 (below 60%)'},latePenalty:'10 points per calendar day; no submissions after 5 days past due date',academicIntegrity:'Per WSU Academic Integrity Policy: all model artifacts must be individually authored'},
    weeklyMCQ:{points:5,closesDay:'Sunday 11:59 PM',instructions:'Auto-graded. 2 attempts; highest score counts. Covers key concepts of Lecture 1. Complete before Sunday 11:59 PM of the lecture week.',questions:[
      {question:'Which INCOSE SE Handbook v5 term describes system-level properties that cannot be attributed to any individual component in isolation?',options:['Functional decomposition','Emergent behavior','Modular architecture','Integration behavior'],correct:1,explanation:'Emergent behavior is the core SE challenge: system properties arise from element interactions. This is the foundational argument for MBSE over component-level analysis. INCOSE SE Handbook v5, Section 2.2.'},
      {question:'The AWRF eVTOL parametric model converges to MTOW = 2,969 kg versus the document-centric 1,722 kg. The primary cause of the 72.4% underestimate is:',options:['Incorrect rotor disk loading equations in the spreadsheet.','The static spreadsheet evaluated the battery mass / structural mass / hover power coupling only once (open-loop) instead of iterating to convergence.','Metric vs imperial unit inconsistency in the document-centric model.','The parametric model used a more conservative safety factor.'],correct:1,explanation:'The weight-snowball coupling — battery mass drives structural mass drives hover power drives battery mass — is iterative. A single-pass evaluation underestimates MTOW because it does not converge the coupled constraint system. SysML parametric binding connectors force iterative convergence to 2,969 kg. Source: Northam & Chen (2024).'},
      {question:'OMG SysML 1.7 defines MBSE as providing four categories of diagram. The category that enables quantitative engineering analysis by encoding equations as constraint blocks is:',options:['Requirements','Structure','Behavior','Parametric'],correct:3,explanation:'The Parametric pillar (Parametric Diagram) is the unique analytical capability of SysML 1.7. Constraint blocks encode engineering equations; binding connectors propagate design variable changes through the constraint network. This is the capability that prevents the eVTOL MTOW underestimation.'},
      {question:'In INCOSE SE Handbook v5 terminology, what distinguishes a stakeholder need from a system requirement?',options:['Needs use "shall" language; requirements use "should" language.','Needs are architecture-agnostic statements of operational intent owned by the customer; requirements are derived, quantified, verifiable statements owned by the SE team.','Needs are documented in the BDD; requirements are documented in the requirements diagram.','There is no distinction — the terms are interchangeable in INCOSE practice.'],correct:1,explanation:'Stakeholder needs are problem-space statements (what the customer needs, independent of solution). System requirements are derived from needs and expressed in engineering language with quantified thresholds, verification methods, and solution-space constraints. Conflating them is a requirements engineering anti-pattern.'},
      {question:'The digital thread concept (DoD Digital Engineering Strategy, 2018) positions the MBSE model as:',options:['A PDF report generated from the model for customer delivery.','The spine of a continuously maintained machine-readable information chain connecting all engineering artifacts from mission concept through operational sustainment.','A backup archive of all program documents.','A visualization tool for management briefings.'],correct:1,explanation:'The digital thread is an end-to-end information continuity concept. The MBSE model is the authoritative source of requirements, architecture, and interface definitions that all downstream tools (CAD, simulation, test management) reference. Changes in the model propagate through the thread to all connected tools.'}
    ]},
    miniProject:{status:'building',dueWeek:8,title:'Mini Project 1: AWRF System Requirements Definition and Structural Architecture',note:'Lecture 1 of 7 pre-MP1 lectures. Full specification available at Lecture 8.'},
  }; // end LECTURE_1_DATA

  /* ──────────────────────────────────────────────────────────────
     Register with the application engine defined in index.html.
     ────────────────────────────────────────────────────────────── */
  if (typeof window.registerLecture === 'function') {
    window.registerLecture(1, LECTURE_1_DATA);
  } else {
    // Fallback: direct injection (if lecture loaded before engine boots)
    window.MBSE_COURSE_DATA = window.MBSE_COURSE_DATA || {};
    window.MBSE_COURSE_DATA[1] = LECTURE_1_DATA;
  }

})();
